#!/usr/bin/env python3
"""Generate the managed-game browser/firmware catalog from versioned receipts."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
ORDER=['bass','queen','soltys','sfinx','lure','teenagent','draci','drascula','nippon','dreamweb','mandy','frasse','cubert','sammax','indy4','kyra2','dig','comi']
SITE_ORDER=['bass','queen','soltys','sfinx','lure','teenagent','draci','drascula','nippon','sammax','indy4','dig','comi']
HUD={'bass':('BENEATH','STEEL SKY'),'queen':('AMAZON','QUEEN'),'soltys':('SOLTYS','POLSKI'),'sfinx':('SFINX','POLSKI'),'lure':('LURE','TEMPTRESS'),'teenagent':('TEEN','AGENT'),'draci':('DRAGON','HISTORY'),'drascula':('DRASCULA','VAMPIRE'),'nippon':('NIPPON','SAFES')}
HUD.update(dreamweb=('DREAM','WEB'),mandy=('MANDY','CHRISTMAS'),frasse=('FRASSE','KEJICK'),cubert=('CUBERT','BADBONE'),sammax=('SAM & MAX','HIT THE ROAD'),indy4=('INDIANA','ATLANTIS'),kyra2=('KYRANDIA','HAND OF FATE'),dig=('THE DIG','LUCASARTS'),comi=('MONKEY','ISLAND'))
profiles={}
for game in ORDER + ['drascula_music']:
 paths=list((ROOT/'manifests').glob(game+'-*.json'))
 if not paths and game not in SITE_ORDER and game != 'drascula_music':
  # The public checkout deliberately omits untested private candidates.
  continue
 assert len(paths)==1, game
 m=json.loads(paths[0].read_text());p=m['source_package']
 profiles[game]={'id':game,'target':m.get('target','sky' if game=='bass' else game),'title':m['title'],'engine':m['engine'],'language':m.get('language','en'),'platform':m.get('platform','dos'),'minimumFirmware':m.get('minimum_firmware',2),'edition':m['edition'],'packageName':p['filename'],'packageSha256':p['sha256'],'packageFormat':p.get('format','pkg'),'sourceUrl':m.get('source_url',f'https://www.gog.com/en/game/{"beneath_a_steel_sky" if game=="bass" else "flight_of_the_amazon_queen"}'),'files':m['files']}
 # Audio pack shares the game directory but has a separate atomic receipt.
 profiles[game].update(kind=m.get('kind','game'),installRoot=m.get('install_root',game),receiptName=m.get('receipt_name','game.json'),markerName=m.get('marker_name','.tab5adv-installing'))
site_profiles={game:profiles[game] for game in SITE_ORDER + ['drascula_music']}
(ROOT/'site/catalog.js').write_text('// Generated by tools/build_catalog.py; edit manifests/*.json.\nexport const GAME_PROFILES = '+json.dumps(site_profiles,ensure_ascii=False,indent=2)+';\n')
lines=['// SPDX-License-Identifier: GPL-3.0-or-later','// Generated by tools/build_catalog.py; edit manifests/*.json.','#pragma once','#include <stdint.h>','namespace Tab5 {','struct RequiredFile { const char *name; uint32_t size; };','struct Game { const char *id,*target,*engine,*title,*language,*platform,*hud1,*hud2; const RequiredFile *files; };']
for game,m in profiles.items():
 if m['kind']=='addon':continue
 lines.append(f'static const RequiredFile {game}Files[] = {{')
 for f in m['files']:lines.append('    {'+json.dumps(f['name'])+', '+str(f['size'])+'},')
 lines.append('    {nullptr,0}};')
lines.append('static const Game games[] = {')
for game,m in profiles.items():
 if m['kind']=='addon':continue
 values=[game,m['target'],m['engine'],m['title'],m['language'],m['platform'],*HUD[game]]
 lines.append('    {'+', '.join(json.dumps(v,ensure_ascii=True) for v in values)+f', {game}Files'+'},')
lines.extend(['};','inline const Game *gameForTarget(const char *target) {','    for (const auto &g:games) if (!strcmp(g.target,target)) return &g;','    return nullptr;','}','}'])
# strcmp declaration is supplied by standard headers on both device and host.
lines.insert(4,'#include <cstring>')
firmware_header=ROOT/'firmware/backends/platform/esp32/main/tab5-games.h'
if firmware_header.parent.is_dir():
 firmware_header.write_text('\n'.join(lines)+'\n')
print('Generated browser and firmware catalogs:',', '.join(ORDER))
